// Generated by CoffeeScript 1.6.3
(function() {
  describe("Element Search", function() {
    return describe("When pseudoGuid is generated", function() {
      return it("should do something", function() {
        return console.log("Hello!");
      });
    });
  });

}).call(this);
